"use client";
import { useEffect } from "react";
import { ArrowRight, BookOpen, Gift, LogIn, Menu, Sparkles, Users } from "lucide-react";
import Lenis from "lenis";

const features = [{ icon: BookOpen, title: "Tools belajar", text: "Kumpulan tools kecil untuk membuat proses belajar terasa lebih ringan." }, { icon: Users, title: "Komunitas", text: "Temukan teman bertumbuh, berbagi insight, dan membuka peluang baru." }, { icon: Gift, title: "Hadiah kejutan", text: "Hal-hal kecil yang disiapkan untuk membuat perjalananmu lebih menyenangkan." }];

export default function Home() {
  useEffect(() => { const lenis = new Lenis({ autoRaf: true, lerp: 0.08 }); return () => lenis.destroy(); }, []);
  return <main className="min-h-screen bg-[#fbf7f0] text-[#33251e]">
    <nav className="mx-auto flex h-[86px] w-[calc(100%-40px)] max-w-[1160px] items-center justify-between" aria-label="Navigasi utama"><a href="#home" className="flex items-center gap-2 text-lg font-bold tracking-tighter"><span className="grid h-7 w-7 rotate-[-11deg] place-items-center rounded-[50%] bg-[#b96f43]"><span className="h-2 w-2.5 rounded-b-lg border-2 border-t-0 border-[#fbf7f0]" /></span>campucino</a><div className="hidden gap-8 text-sm text-[#796a61] md:flex"><a className="font-bold text-[#33251e]" href="#home">Home</a><a href="#tools">Tools</a><a href="#gift">Gift</a></div><div className="hidden items-center gap-5 text-sm md:flex"><a className="flex items-center gap-1.5 text-[#796a61]" href="#community"><LogIn size={16} />Login</a><a className="flex items-center gap-2 rounded-full border border-[#33251e] px-4 py-2 text-xs font-bold" href="#community">Join community <ArrowRight size={15} /></a></div><button className="md:hidden" aria-label="Buka menu"><Menu size={21} /></button></nav>
    <section id="home" className="mx-auto grid min-h-[620px] w-[calc(100%-40px)] max-w-[1160px] items-center gap-12 py-16 md:grid-cols-2 md:gap-16"><div><div className="mb-5 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.16em] text-[#b96f43]"><Sparkles size={15} />ruang kecil untuk tumbuh besar</div><h1 className="mb-7 text-6xl font-bold leading-[.98] tracking-[-.075em] md:text-7xl">Belajar lebih seru,<br /><em className="font-serif font-normal text-[#b96f43]">bareng-bareng.</em></h1><p className="max-w-[410px] text-[15px] leading-7 text-[#796a61]">Campucino Community adalah tempat bertemu, berbagi, dan bertumbuh untuk kamu yang sedang membangun versi terbaik dari diri sendiri.</p><div className="mt-8 flex items-center gap-6"><a className="flex items-center gap-3 rounded-full bg-[#33251e] px-5 py-3.5 text-xs font-bold text-[#fbf7f0]" href="#community">Mulai eksplorasi <ArrowRight size={17} /></a><a className="border-b border-[#33251e] pb-1 text-xs font-bold" href="#tools">Lihat tools ↗</a></div></div><div className="relative h-[380px] overflow-hidden rounded-[48%] bg-[#f2e5d4] md:h-[470px]"><div className="absolute right-0 top-0 h-56 w-56 rounded-full bg-[#e8c49c]" /><div className="absolute bottom-24 left-1/2 h-44 w-48 -translate-x-1/2 rotate-[-4deg]"><div className="absolute left-1 top-1 z-10 h-11 w-44 rounded-[50%] border-[9px] border-[#ead2b4] bg-[#6f402d]" /><div className="absolute left-3 top-6 h-32 w-40 rounded-b-[48px] rounded-t-xl bg-[#fffaf2]" /><div className="absolute right-0 top-12 h-16 w-14 rounded-r-[42px] border-[16px] border-l-0 border-[#fffaf2]" /></div><div className="absolute bottom-7 left-[12%] rotate-[-8deg] font-serif text-xs">take a little break<br /><strong className="font-normal text-[#b96f43]">you&apos;re doing fine</strong></div><span className="absolute left-[13%] top-1/4 text-2xl text-[#b96f43]">✦</span></div></section>
    <section id="community" className="mx-auto w-[calc(100%-40px)] max-w-[1160px] py-24 md:py-32"><div className="text-[10px] font-bold uppercase tracking-[.16em] text-[#b96f43]">kenalan dulu</div><div className="mt-5 grid gap-7 md:grid-cols-[1.15fr_.85fr] md:gap-16"><h2 className="text-4xl font-bold leading-none tracking-[-.065em] md:text-6xl">Tempat nyaman untuk<br /><em className="font-serif font-normal text-[#b96f43]">ide-ide yang bertumbuh.</em></h2><p className="max-w-sm self-end text-sm leading-7 text-[#796a61]">Kami percaya proses yang baik tidak harus selalu terasa serius. Di sini, kamu bisa belajar hal baru, menemukan inspirasi, dan ngobrol dengan orang-orang yang punya rasa penasaran yang sama.</p></div></section>
    <section id="tools" className="mx-auto w-[calc(100%-40px)] max-w-[1160px] pb-24 md:pb-32"><div className="mb-11 grid gap-7 md:grid-cols-[1.15fr_.85fr] md:gap-16"><div><div className="text-[10px] font-bold uppercase tracking-[.16em] text-[#b96f43]">yang tersedia di sini</div><h2 className="mt-5 text-4xl font-bold leading-none tracking-[-.065em] md:text-6xl">Mulai dari<br /><em className="font-serif font-normal text-[#b96f43]">hal sederhana.</em></h2></div><p className="max-w-sm self-end text-sm leading-7 text-[#796a61]">Pelan-pelan, satu langkah kecil setiap hari. Fitur-fitur baru akan terus hadir untuk menemani perjalananmu.</p></div><div className="grid gap-4 md:grid-cols-3">{features.map(({ icon: Icon, title, text }) => <article key={title} className="group relative min-h-64 rounded-2xl bg-[#f2e5d4] p-7 transition hover:-translate-y-1"><div className="mb-12 grid h-11 w-11 place-items-center rounded-full bg-[#fbf7f0] text-[#b96f43]"><Icon size={22} /></div><h3 className="mb-2 text-lg font-bold">{title}</h3><p className="max-w-[240px] text-[13px] leading-6 text-[#796a61]">{text}</p><span className="absolute right-7 top-7 text-xl">↗</span></article>)}</div></section>
    <section id="gift" className="mx-auto grid w-[calc(100%-40px)] max-w-[1160px] items-center gap-5 rounded-3xl bg-[#33251e] p-8 text-[#fbf7f0] md:grid-cols-[auto_1fr_1fr] md:p-11"><Gift className="text-[#b96f43]" size={25} /><div><div className="text-[10px] font-bold uppercase tracking-[.16em] text-[#b96f43]">sedikit kejutan</div><h2 className="mt-1 text-2xl font-bold tracking-tight">Hal baik sedang disiapkan.</h2></div><p className="max-w-xs text-[13px] leading-6 text-[#c9bdb4]">Fitur gift akan segera hadir. Sementara itu, simpan rasa penasaranmu.</p></section>
    <footer className="mx-auto flex w-[calc(100%-40px)] max-w-[1160px] flex-col items-start justify-between gap-5 py-16 text-[11px] text-[#796a61] md:flex-row md:items-center"><a href="#home" className="font-bold text-[#33251e]">☕ campucino</a><span>made with care for curious minds · 2026</span></footer>
  </main>;
}
